## activemq-artemis image version
## ref: https://hub.docker.com/r/vromero/activemq-artemis/tags
##
imageTag: "1.6.0"

## Specify password for root user
##
## Default: random 10 character string
# mysqlRootPassword: testing

## Create a database user
##
# artemisUser:
# artemisPassword:

## Specify an imagePullPolicy (Required)
## It's recommended to change this to 'Always' if the image tag is 'latest'
## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
##
#imagePullPolicy: IfNotPresent
imagePullPolicy: Always

replicas: 2

## Persist data to a persitent volume
persistence:
  testJournalPerformance: AUTO
  enabled: false
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m
