apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artemis.fullname" . }}-configure-slave
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
data:

  template-slave.xml: |
    <configuration xmlns="urn:activemq" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:activemq /schema/artemis-configuration.xsd">
      <core xmlns="urn:activemq:core" xsi:schemaLocation="urn:activemq:core ">
         <ha-policy>
          <replication>
            <slave>
              <group-name>to-be-set-by-configure-cluster.sh</group-name>
            </slave>
          </replication>
        </ha-policy>
      </core>
    </configuration>

  configure-cluster.sh: |
    
    {{ $name := default .Chart.Name .Values.nameOverride }}
    {{ $releaseName := printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}

    MASTERNAME=$(echo ${HOSTNAME} | sed -re 's/-slave/-master/g')

    set -e
    echo Copying common configuration
    cp /opt/configure-common/template-common.xml /var/lib/artemis/etc-override/broker-10.xml

    echo Assigning node as slave
    cp /opt/configure-slave/template-slave.xml /var/lib/artemis/etc-override/broker-11.xml 

    GROUPNAME=$(echo ${HOSTNAME} | sed -re 's/(-slave|-master)//')
    echo Setting the group-name for slave to ${GROUPNAME}
    xmlstarlet ed -L \
    -N activemq="urn:activemq" \
    -N core="urn:activemq:core" \
    -u "/activemq:configuration/core:core/core:ha-policy/core:replication/core:slave/core:group-name" \
    -v "${GROUPNAME}" /var/lib/artemis/etc-override/broker-11.xml

    echo Setting the connector-ref to ${HOSTNAME}
    xmlstarlet ed -L \
    -N activemq="urn:activemq" \
    -N core="urn:activemq:core" \
    -u "/activemq:configuration/core:core/core:cluster-connections/core:cluster-connection[@name='{{ $releaseName }}']/core:connector-ref" \
    -v "${HOSTNAME}" /var/lib/artemis/etc-override/broker-10.xml